version: 0.0
os: linux

files:
  - source:  /
    destination: /home/ubuntu/face-backend
    overwrite: yes

permissions:
  - object: /
    owner: ubuntu
    group: ubuntu

hooks:

  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 60

  ApplicationStart:
    - location: scripts/start.sh
      timeout: 60
